spring.application.name=L2-S2-Project
spring.datasource.url=jdbc:mysql://localhost:3306/zynova_db
spring.datasource.username=root
spring.datasource.password=Pasiya@2002
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.jdbc.dialect=mysql
spring.jpa.properties.hibernate.format_sql=true


stripe.apiKey=sk_test_51Oy4eAJ10XzAyuHYmz221xxCNLX0VTVUREclktNumRtJDtvPS1jAU8aw2pZ49N56moqm9Yf2Vbe7jF4efxhYp0NS00W4ktuIv9


